### ISSUE TITLE
'AsyncSignal' object is not callable

### ISSUE THREAD

**Issue by chokosabe** [nyergler/async-signals#2]
Im trying this with celery 3.1.17 and django 1.67.

from the django shell I try the steps in the docs:

from async_signals.signals import request_started
request_started(None)

This results in the error:

'AsyncSignal' object is not callable

**Comment by nyergler** [comment]
You need to call the `send` method, as stated in the README:

```
>>> from async_signals.signals import request_started
>>> request_started.send(None)
```

**Comment by chokosabe** [comment]
I get this error when trying what you put above:

[2014-12-30 15:14:15,087: ERROR/MainProcess] Task async_signals.dispatcher.propagate_signal[c7a437fd-b9f9-412d-a054-458cd67a44fc] raised unexpected: TypeError('propagate_signal() takes exactly 2 arguments (0 given)',)
Traceback (most recent call last):
  File "/home/app/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/home/app/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
TypeError: propagate_signal() takes exactly 2 arguments (0 given)
